#!/bin/bash
# Copyright Janet Davis 2019 CC-BY-NC-SA (such as it is!)

#NEXT TIME: Increase points for final tests of jump logic; 
#           Decrease points for running programs

# A-instruction, PC increment  8
# D-register                   3
# A-register                   3
# ALU                          3
# Memory write                 3
# Memory read                  3
# JLT                          2
# Do not jump on A-instruction 2
# JEQ                          2
# JGT                          2
# All jumps                    2

passed=$1

if [[ $passed -lt 2 ]]; then
    echo "0"
    echo "Test failure: @12345. Working: Compiles."
elif [[ $passed -lt 4 ]]; then
    echo "8"
    echo "Test failure: D=A. Working: A-Instruction, PC increment."
elif [[ $passed -lt 8 ]]; then
    echo "11"
    echo "Test failure: D=A-D: Working: A-instruction, PC increment, D-Register. Probably working: ALU."
elif [[ $passed -lt 10 ]]; then
    echo "14"
    echo "Test failure: A=D: Working: A-instruction, PC increment, D-Register. Probably working: ALU."
elif [[ $passed -lt 12 ]]; then
    echo "17"
    echo "Test failure: M=D. Working: A-instruction, PC increment, D-Register, A-Register. Probably working: ALU."
elif [[ $passed -lt 20 ]]; then    
    echo "20"
    echo "Test failure by D=D-M. Working: A-instruction, PC increment, D-Register, A-Register. Probably working: ALU, memory write."
elif [[ $passed -lt 24 ]]; then    
    echo "23"
    echo "Test failure by D;jlt. Working: A-instruction, PC increment, D-Register, A-Register. Probably working: ALU, memory read/write."
elif [[ $passed -lt 28 ]]; then
    echo "25"
    echo "Test failure: A=A+1. Working: A-instruction, PC increment, D-Register, A-Register. Probably working: ALU, memory read/write. Partly working: Jumps."
elif [[ $passed -lt 34 ]]; then
    echo "27"
    echo "Test failure by D+1;jeq. Working: A-instruction, PC increment, D-Register, A-Register. Probably working: ALU, memory read/write. Partly working: Jumps."
elif [[ $passed -lt 44 ]]; then
    echo "29"
    echo "Test failure by D;JGT. Working: A-instruction, PC increment, D-Register, A-Register. Probably working: ALU, memory read/write. Partly working: Jumps."
elif [[ $passed -lt 48 ]]; then
    echo "31"
    echo "Test failure by D;JGE. Working: A-instruction, PC increment, D-Register, A-Register. Probably working: ALU, memory read/write. Partly working: Jumps."
else
    echo "33"
    echo "Working: A-instruction, PC increment, D-Register, A-Register, A-Register. Probably working: ALU, memory read/write, jumps. Contact Prof. Davis if you are concerned about the last point!"
fi
